name: namegenerator
description: 彼岸自在

publish_to: 'none'
version:  0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  package_info: ^0.4.1
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/pluto-payment-processed.png
    - assets/images/kingdom-4.png
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: genkai-mincho
      fonts:
        - asset: assets/fonts/genkai-mincho.ttf
    - family: NijimiMincho
      fonts:
        - asset: assets/fonts/NijimiMincho.ttf
