name: bianzizai
description: 彼岸自在

publish_to: "none"
version: 1.3.2+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  package_info: ^2.0.0
  provider: ^5.0.0
  transparent_image: ^2.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  image_picker: ^0.7.4
  webview_flutter: ^2.0.4
  url_launcher: ^6.0.3
  flutter_screenutil: ^5.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  share: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  like_button: ^2.0.2
  tobias: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/theme/japanese-default-theme.png
    - assets/images/theme/chinese-default-theme.png
    - assets/images/theme/shadiao-default-theme.jpg
    - assets/images/theme/english-default-theme.png
    - assets/images/theme/couples.png
    - assets/images/search/bg1.png
    - assets/images/search/bg2.png
    - assets/images/search/bg3.png
    - assets/images/search/bg4.png
    - assets/images/search/bg5.png
    - assets/images/search/card1.png
    - assets/images/search/card2.png
    - assets/images/search/card3.png
    - assets/images/search/card4.png
    - assets/images/search/card5.png
    - assets/images/login/login.png
    - assets/images/about/about.png
    - assets/images/inspiration/top.png
    - assets/images/inspiration/middle.png
    - assets/images/vip/vip.png
    - assets/images/vip/vip_tip.png
    - assets/images/vip/vip_budge.png
    - assets/images/vip/vip_budge_grey.png
    - assets/images/vip/discount.png
    - assets/images/vip/vip_bg.png
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: SoukouMincho
      fonts:
        - asset: assets/fonts/SoukouMincho.ttf
