name: bianzizai
description: 彼岸自在

publish_to: "none"
version: 1.0.7+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  package_info: ^0.4.3
  provider: ^4.3.2+2
  transparent_image: ^1.0.0
  path_provider: ^1.6.18
  shared_preferences: ^0.5.12
  image_picker: ^0.6.7+11
  webview_flutter: ^1.0.1
  url_launcher: ^5.7.2
  flutter_screenutil: ^3.1.1
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  share: ^0.6.5+2
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/pluto-payment-processed.png
    - assets/images/peach__blossom.png
    - assets/images/pluto-searching.png
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: SoukouMincho
      fonts:
        - asset: assets/fonts/SoukouMincho.ttf
    - family: NijimiMincho
      fonts:
        - asset: assets/fonts/NijimiMincho.ttf
