name: bianzizai
description: 彼岸自在

publish_to: "none"
version: 1.2.5+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  package_info: ^0.4.3+2
  provider: ^4.3.2+4
  transparent_image: ^1.0.0
  path_provider: ^1.6.27
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+21
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  flutter_screenutil: ^4.0.2+5
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  share: ^0.6.5+4
  flutter_staggered_grid_view: ^0.3.3
  like_button: ^1.0.4
  tobias: ^1.7.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/theme/japanese-default-theme.png
    - assets/images/theme/chinese-default-theme.png
    - assets/images/theme/cute-default-theme.png
    - assets/images/theme/couples.png
    - assets/images/search/bg1.png
    - assets/images/search/bg2.png
    - assets/images/search/bg3.png
    - assets/images/search/bg4.png
    - assets/images/search/bg5.png
    - assets/images/search/card1.png
    - assets/images/search/card2.png
    - assets/images/search/card3.png
    - assets/images/search/card4.png
    - assets/images/search/card5.png
    - assets/images/login/login.png
    - assets/images/about/about.png
    - assets/images/inspiration/top.png
    - assets/images/inspiration/middle.png
    - assets/images/vip/vip.png
    - assets/images/vip/vip_tip.png
    - assets/images/vip/vip_budge.png
    - assets/images/vip/vip_budge_grey.png
    - assets/images/vip/discount.png
    - assets/images/vip/vip_bg.png
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: SoukouMincho
      fonts:
        - asset: assets/fonts/SoukouMincho.ttf
