name: bianzizai
description: 彼岸自在

publish_to: "none"
version: 1.0.9+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  package_info: ^0.4.3
  provider: ^4.3.2+2
  transparent_image: ^1.0.0
  path_provider: ^1.6.21
  shared_preferences: ^0.5.12+2
  image_picker: ^0.6.7+12
  webview_flutter: ^1.0.3
  url_launcher: ^5.7.5
  flutter_screenutil: ^3.1.1
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  share: ^0.6.5+3
  flutter_staggered_grid_view: ^0.3.2
  like_button: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/theme/japanese-default-theme.png
    - assets/images/theme/chinese-default-theme.png
    - assets/images/login/login.png
    - assets/images/about/about.png
    - assets/images/inspiration/top.png
    - assets/images/inspiration/middle.png
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: SoukouMincho
      fonts:
        - asset: assets/fonts/SoukouMincho.ttf
    - family: NijimiMincho
      fonts:
        - asset: assets/fonts/NijimiMincho.ttf
